### ISSUE TITLE
Access to Internet 

### ISSUE THREAD

**Issue by linqinyu** [GeoDaCenter/opioid-policy-scan#15]
##B28002_001: Estimate!!Total:
##B28002_002: Estimate!!Total:!!Estimate!!Total:!!With an Internet subscription
##B28002_012: Estimate!!Total:!!Internet access without a subscription
##B28002_013: Estimate!!Total:!!No Internet access

We can calculate % of households without access to the Internet using B28002_013/B28002_001.

**Comment by Makosak** [comment]
@linqinyu if complete, feel free to close out!

**Comment by spaykin** [comment]
@linqinyu closing this!
