### ISSUE TITLE
New metadata file is needed.

### ISSUE THREAD

**Issue by wam0** [GeoDaCenter/opioid-policy-scan#151]
The following variables in data of the Census Tract scale do not appear in any metadata files. We will have to create new metadata files for them.

SocEcAdvIn
LimMobInd
UrbCoreInd
MicaInd

**Comment by wam0** [comment]
@Makosak will check it!

**Comment by mradamcox** [comment]
These are the variables from the [SDOH Atlas](https://sdohatlas.github.io/index.html).

**Comment by mradamcox** [comment]
I have added these to the existing metadata document that referenced the SDOH Atlas, which to this point only mentioned the Neighborhood Typologies variable.
