### ISSUE TITLE
OTP distance data appears incorrect at ZCTA scale

### ISSUE THREAD

**Issue by ccsarapas** [GeoDaCenter/opioid-policy-scan#160]
For example, plotting driving times to nearest OTP at the tract level (left panel) appears to correspond to locations of OTPs, but by ZCTA (right panel) doesn't:

![image](https://github.com/user-attachments/assets/80b6be6b-787c-4e7c-bd3b-3b32f4683b6d)

Looking at the data, ZCTAs with lower distances have _higher_ drive times. Plus the count of OTPs within 30 minutes has fractional numbers, which doesn't seem to make sense.
```
# A tibble: 1,383 × 4
   GEOID OtpMinDis OtpTmDr OtpCntDr
   <chr>     <dbl>   <int>    <dbl>
 1 60002      9.22       4    17.4
 2 60004      4.2       10    10.9
 3 60005      4.3       13     7.51
 4 60007      8.1       14    12.3
 5 60008      1.89      12     0
 6 60010     10.5        6    20.6
 7 60012     15.0        0    30.2
 8 60013     14.4        1    28.3
 9 60014     15.3        1    26.0
10 60015      9.5       11    16.0
# ℹ 1,373 more rows
```
Other drive time variables (e.g., FQHCs, MOUD providers) at the ZCTA level seem correct, it's just the OTPs.

**Comment by mradamcox** [comment]
@ccsarapas we've been discussing this on our end, at first were thinking we may need to recalculate these variables... However, now I just realized something related to your second point: What if the `OtpTmDr` and `OtpCntDr` just got swapped in our data? That would explain the field type strangeness you noted (`OtpTmDr` should be `dbl` and `OtpCntDr` should be `int`), and just looking at the numbers here, it could physically make sense too. What do you think?

FWIW I have learned more about these variables from looking into this issue, so just to point a few things out that are in the [metadata](https://github.com/GeoDaCenter/opioid-policy-scan/blob/main/data_final/metadata/Access_OpioidUseTreatment.md) but I didn't fully understand at first:

- `OtpMinDis`: is the euclidean distance from the centroid of the ZCTA to the nearest OTP
- `OtpTmDr`: is the driving time (via road network) from the centroid of the ZCTA to the centroid of the ZCTA that holds the nearest OTP
- `OtpCntDr` is the number of OTPs within 30 minutes driving... which, I'm assuming would be need to be interpreted as "from the centroid of this ZCTA how many others can you drive to the centroid of within 30 minutes, and now sum the totals of OTPs within all those ZCTAs"

**Comment by ccsarapas** [comment]
@mradamcox I wondered about that too...

One check might be to look at the relationship with the methadone access variables -- since OTPs are the only providers authorized to dispense methadone, they should be pretty strongly correlated. And this is in fact the case in the tract-level data -- correlating `Met` access variables with equivalent `Otp` variables, the strongest correlations are on the diagonal:
```r
library(tidyverse)
library(oepsData)

tracts <- load_oeps("tract", year = 2018, themes = "Environment")

tracts %>%
  select(MetMinDis, MetTmDr, MetCntDr30, OtpMinDis, OtpTmDr, OtpCntDr) %>%
  cor(use = "pairwise.complete.obs") %>%
  round(2) %>%
  subset(
    subset = str_starts(rownames(.), "Met"),
    select = str_starts(colnames(.), "Otp")
  )
#            OtpMinDis OtpTmDr OtpCntDr
# MetMinDis       0.96    0.84    -0.27
# MetTmDr         0.87    0.94    -0.35
# MetCntDr30     -0.18   -0.31     0.99
```
But this isn't the case in in the ZCTA data; instead, `MetTmDr` is correlated with `OtpCntDr`, and `MetCntDr30` with `OtpTmDr`:
```r
zcta <- load_oeps("zcta", year = 2018, themes = "Environment")

zcta %>%
  select(MetMinDis, MetTmDr, MetCntDr30, OtpMinDis, OtpTmDr, OtpCntDr) %>%
  cor(use = "pairwise.complete.obs") %>%
  round(2) %>%
  subset(
    subset = str_starts(rownames(.), "Met"),
    select = str_starts(colnames(.), "Otp")
  )
#            OtpMinDis OtpTmDr OtpCntDr
# MetMinDis       0.96   -0.25     0.81
# MetTmDr         0.87   -0.36     0.95
# MetCntDr30     -0.23    0.99    -0.31
```
This does seem to suggest that `OtpTmDr` and `OtpCntDr` are swapped.

**Comment by mradamcox** [comment]
Thanks @ccsarapas I see what you mean about the correlation, and indeed I think these two columns just got switched in one of the data management operations upstream. I'll look further into fixing this and will close the ticket once I have the updated data committed to this repo. Thanks again for your help!

**Comment by mradamcox** [comment]
Ok I found the place where the names got switched, during an column renaming operation that we did last summer, that was based on [this lookup table](https://github.com/GeoDaCenter/opioid-policy-scan/blob/14b537d666d4261fb4a48250acb35713633d075b/data_raw/rename_tables/zip.csv#L117). I'll go ahead and swap the columns directly in the CSV and also update that lookup table.
