### ISSUE TITLE
Opioid prescription & mortality rates

### ISSUE THREAD

**Issue by spaykin** [GeoDaCenter/opioid-policy-scan#23]
2018 data, via HepVu: https://hepvu.org/opioid-prescription-and-overdose-mortality-rates-in-the-u-s-at-the-county-level/

**Comment by Makosak** [comment]
@spaykin if complete, feel free to close out!

**Comment by spaykin** [comment]
Added: https://github.com/GeoDaCenter/opioid-policy-scan/blob/master/data_final/metadata/OpioidIndicators.md
