### ISSUE TITLE
Zip Code Straight-line Distance to All MOUD Data Errors

### ISSUE THREAD

**Issue by nofurtherinformation** [GeoDaCenter/opioid-policy-scan#34]
Some zip codes / ZCTAs appear to have much higher distances reported. This issue is only relevant for zip codes/zcta data for the variable `Distance (mi) to nearest MOUD (all)`
![image](https://user-images.githubusercontent.com/10041771/163599451-a8597839-a22a-49cb-a914-ebf39c62747e.png)
![image](https://user-images.githubusercontent.com/10041771/163599469-46392ee3-d2a1-45be-859f-5457bebc445d.png)

**Comment by spaykin** [comment]
Just re-ran straight line distance metric, merged with data, pushed to explorer. Checked and appears to be resolved (data is updated and more consistent).
