### ISSUE TITLE
Add Triplicate States?

### ISSUE THREAD

**Issue by Predict-This** [GeoDaCenter/opioid-policy-scan#44]
Hello! Relatively simple and powerful addition to this resource would be to add a shapefile or simple dataset of Triplicate States. See https://academic.oup.com/qje/article-abstract/137/2/1139/6427381?redirectedFrom=fulltext&login=true for the powerful contribution of this program to prescription deterrence.  "We find that OxyContin distribution was more than 50% lower in “triplicate states” in the years after OxyContin's launch."

**Comment by Makosak** [comment]
This sounds reasonable! Will start process of data sourcing for this.

**Comment by mradamcox** [comment]
I've replicated this ticket in our new repository, https://github.com/healthyregions/oeps/issues/74, closing now.
