### ISSUE TITLE
Proposal: Split explorer branch into new repository

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/opioid-policy-scan#48]
I've been reading through this repo and its accompanying wiki and other documentation in order to understand it better (which is thorough and really helpful), and I'd like to propose that the `explorer` branch, which holds the static website and is deployed through Netlify, is split into a separate repository. Here are a few reasons I think this would be a good move:

- As it is, the `explorer` branch is completely independent of the `main` branch, and CSV files are manually copied from `main` to `explorer` for publication, or fetch calls in `explorer` access content in `main` through direct calls to `https://github.raw....`, so there is no functional logic to link the two (I may be missing something though).
- Archives of the `main` branch are published to Zenodo (one per release) and associated with a DOI.
    - This means that release tags on this repo get tied to versions in Zenodo of the same DOI, so tagging releases of the `explorer` branch isn't really possible, at least without adding a good bit of confusion to the release lineage.
    - This also means that significant functional changes to the `main` branch, like moving the  `explorer` codebase into it as a subdirectory, seem inappropriate.
- Similarly, we will need to make changes to the explorer website in the future, at the very least to set netlify configs like pinning a node version (for example, the deployment/build process seems to break with node >= 17 (or so), due to an [openssl issue](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported), thanks @bucketteOfIvy for finding this), so developing on the main branch of a new repo will be generally less cumbersome and more sustainable.

We should be able to clone the branch independently into a new repo while retaining all relevant commit history--the process would be [something like this](https://mattbanderson.com/migrating-a-branch-between-git-repositories-and-preserving-history/) not just a copy-paste into a new blank repo. This means that **all past contribution history would remain intact** (this is a requirement as far as I'm concerned).

I'm thinking the new repo would be something like `healthyregions/oeps-explorer`.

Anyway, I'm writing this ticket out mostly to get the idea in front of @spaykin and @nofurtherinformation, as you have been the main contributors to this repo, and I don't think a change like this can happen without your input. Like I mentioned, work will definitely need to happen on the explorer at some point this summer, so this is essentially a preparatory step for that.

---

to complete:
- [x] resolve `explorer-debug` branch (merge into `explorer`, or just document and delete?)
- [x] create new repo as described above
- [x] update this repo's readme as needed
- [x] update this repo's wiki as needed
- [x] look around for references to the explorer in other literature and update urls
- [x] setup netlify build from new repo (this may include a domain change as well)
- [x] delete `explorer` branch from this repo

**Comment by spaykin** [comment]
@mradamcox This is all fine with me. Thank you for laying out your proposal and thinking behind it. From both a technical and long-term sustainability perspective, it makes sense.

**Comment by mradamcox** [comment]
@spaykin Sounds good. I'll start working on it soon and leave this ticket open until it's get it all squared away.

**Comment by mradamcox** [comment]
I've created a new repository from the branch as described (much easier than I was thinking it would be): https://github.com/healthyregions/oeps-explorer. However, before going further with the rest of this ticket, I think we need to address the build issue, which is tracked in https://github.com/healthyregions/oeps-explorer/issues/1. That way we can get a staging deployment of the new location setup and do a cleaner switch when the urls change.

**Comment by mradamcox** [comment]
After a few different attempts at redirect configuration, the new deployment is fully up and running at https://oeps.healthyregions.org and deployed from the new repo. Final tasks here are to update the readme, etc. and remove the explorer branch.

**Comment by mradamcox** [comment]
All tasks now completed. There was just one commit in the `explorer-debug` branch, marking it here for future reference: https://github.com/GeoDaCenter/opioid-policy-scan/commit/ea8eb285e0164587f1e0717ffde8f514d495beab
