### ISSUE TITLE
Update metadata files for 2.0 release

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/opioid-policy-scan#75]
We discussed how to approach the metadata update that is needed now that a lot of files structures and dictionaries have changed. The approach we agreed upon has two parts which are described below. Note: the new data dictionaries are in XSLX format, and can be found here: https://github.com/GeoDaCenter/opioid-policy-scan/tree/main/data_final/dictionaries. These will be helpful references for step 1 and in step 2 they will need to be updated. (These steps are more suggestion for how to go about the process, not required workflow).

This only concerns all _non-geography_ markdown metadata files.

## 1 . Update all existing metadata markdown files.

The files here: https://github.com/GeoDaCenter/opioid-policy-scan/tree/main/data_final/metadata from v1 are still very much relevant after the reorganization, but they need to be updated in the following ways:

- Update variable names where necessary
    - We standardized a lot of variable names, see these lookup files for reference: https://github.com/GeoDaCenter/opioid-policy-scan/tree/main/data_raw/rename_tables
- Update Themes where necessary
  - Match to values in the data dictionaries
  - Edit: On further inspection, these themes are handled elsewhere, outside of the markdown files. So this step will be handled in a different ticket.
- Update author/modified like so:
    ```
   Author: <original author>
   Last Modified: <new date>
   Last Modified By: <updater>
    ```

## 2. Add `Metadata Location` column to the new Data Dictionaries

A new `Metadata Location` column will be added to each of the new XLSX data dictionaries, with a URL pointing to the GitHub-hosted location of the corresponding Markdown file for each variable row. These should be the "raw" urls referencing the main branch (we'll update to the 2.0 tag later, just before creating that release). For example:

    https://raw.githubusercontent.com/GeoDaCenter/opioid-policy-scan/main/data_final/metadata/Access_FQHCs_MinDistance.md

This will also offer a good QA/QC opportunity for whether we are missing markdown files: each row must have a value for `Metadata Location`.

**Comment by mradamcox** [comment]
@wam0 Has noted some variables that we need to take a closer look at:

See note in https://github.com/GeoDaCenter/opioid-policy-scan/pull/76

See swapped minute times here:
![image](https://github.com/GeoDaCenter/opioid-policy-scan/assets/10427268/63202852-0d3d-4518-a91f-2fdd884189d3)

**Comment by mradamcox** [comment]
see also: https://github.com/GeoDaCenter/opioid-policy-scan/pull/117
see also: https://github.com/GeoDaCenter/opioid-policy-scan/pull/111

**Comment by wam0** [comment]
Here is the comment on how to update the theme.
The following part is added after the editor's information.

```
### Theme: 
<theme of the data>  
```

**Comment by wam0** [comment]
In State scale data, the following two variables are not Pascal Case. It might need to be modified.
blkHcv
nonBlkHcv

**Comment by wam0** [comment]
"Historical_Methadone_point.md" needs to be updated.
https://github.com/GeoDaCenter/opioid-policy-scan/blob/main/data_final/metadata/Historical_Methadone_point.md

The locational data in 1984 can be added.
